//
//  DemoScene.swift
//  VisionBox
//

import UIKit

/// A bundled Demo Mode scene: a self-created, license-safe image plus
/// hand-authored detections whose boxes match the image content.
///
/// The images are generated by `Tools/GenerateDemoImages.swift`, which draws
/// every object inside the exact normalized rectangles listed below — so the
/// boxes and the artwork agree by construction. IDs are deterministic so
/// screenshots, previews, and tests stay stable.
nonisolated struct DemoScene: Identifiable, Equatable, Sendable {
    let id: String
    let title: String
    let imageName: String
    let detections: [DetectedObject]

    /// The bundled demo image, ready for display.
    var image: UIImage? {
        UIImage(named: imageName)
    }

    /// The bundled image's raw bytes — the same "prepared image data" the
    /// detection seam expects, and how `DemoDetectionService` recognizes
    /// which scene is being analyzed.
    var imageData: Data? {
        Bundle.main.url(forResource: imageName, withExtension: "png")
            .flatMap { try? Data(contentsOf: $0) }
    }
}

nonisolated extension DemoScene {

    static let all: [DemoScene] = [.desk, .kitchen, .everydayCarry]

    static let desk = DemoScene(
        id: "desk",
        title: "Desk Setup",
        imageName: "demo-desk",
        detections: [
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000101")!,
                label: "Laptop",
                confidence: 0.97,
                boundingBox: BoundingBox(x: 0.30, y: 0.28, width: 0.34, height: 0.42)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000102")!,
                label: "Notebook",
                confidence: 0.88,
                boundingBox: BoundingBox(x: 0.08, y: 0.55, width: 0.20, height: 0.28)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000103")!,
                label: "Pen",
                confidence: 0.74,
                // Nested inside the notebook's box — exercises smallest-box-wins.
                boundingBox: BoundingBox(x: 0.115, y: 0.66, width: 0.125, height: 0.038)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000104")!,
                label: "Coffee Mug",
                confidence: 0.92,
                boundingBox: BoundingBox(x: 0.70, y: 0.54, width: 0.11, height: 0.17)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000105")!,
                label: "Potted Plant",
                confidence: 0.86,
                boundingBox: BoundingBox(x: 0.585, y: 0.16, width: 0.13, height: 0.30)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000106")!,
                label: "Smartphone",
                confidence: 0.95,
                boundingBox: BoundingBox(x: 0.845, y: 0.58, width: 0.075, height: 0.20)
            ),
        ]
    )

    static let kitchen = DemoScene(
        id: "kitchen",
        title: "Kitchen Counter",
        imageName: "demo-kitchen",
        detections: [
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000201")!,
                label: "Cutting Board",
                confidence: 0.93,
                boundingBox: BoundingBox(x: 0.10, y: 0.55, width: 0.52, height: 0.28)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000202")!,
                label: "Chef's Knife",
                confidence: 0.89,
                // Lies on the cutting board — nested for smallest-box-wins.
                boundingBox: BoundingBox(x: 0.16, y: 0.615, width: 0.34, height: 0.08)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000203")!,
                label: "Tomato",
                confidence: 0.84,
                boundingBox: BoundingBox(x: 0.66, y: 0.68, width: 0.16, height: 0.12)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000204")!,
                label: "Mixing Bowl",
                confidence: 0.90,
                boundingBox: BoundingBox(x: 0.64, y: 0.42, width: 0.30, height: 0.20)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000205")!,
                label: "Frying Pan",
                confidence: 0.91,
                boundingBox: BoundingBox(x: 0.34, y: 0.20, width: 0.58, height: 0.22)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000206")!,
                label: "Olive Oil Bottle",
                confidence: 0.87,
                boundingBox: BoundingBox(x: 0.10, y: 0.13, width: 0.15, height: 0.33)
            ),
        ]
    )

    static let everydayCarry = DemoScene(
        id: "carry",
        title: "Everyday Carry",
        imageName: "demo-carry",
        detections: [
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000301")!,
                label: "Backpack",
                confidence: 0.96,
                boundingBox: BoundingBox(x: 0.06, y: 0.14, width: 0.26, height: 0.64)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000302")!,
                label: "Camera",
                confidence: 0.94,
                boundingBox: BoundingBox(x: 0.40, y: 0.18, width: 0.20, height: 0.26)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000303")!,
                label: "Headphones",
                confidence: 0.92,
                boundingBox: BoundingBox(x: 0.68, y: 0.12, width: 0.24, height: 0.34)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000304")!,
                label: "Passport",
                confidence: 0.85,
                boundingBox: BoundingBox(x: 0.42, y: 0.56, width: 0.13, height: 0.26)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000305")!,
                label: "Sunglasses",
                confidence: 0.81,
                boundingBox: BoundingBox(x: 0.62, y: 0.60, width: 0.22, height: 0.13)
            ),
            DetectedObject(
                id: UUID(uuidString: "00000000-0000-0000-0000-000000000306")!,
                label: "Water Bottle",
                confidence: 0.89,
                boundingBox: BoundingBox(x: 0.875, y: 0.50, width: 0.085, height: 0.42)
            ),
        ]
    )
}
